services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - capture_network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  celery-beat:
    build: .
    command: celery -A celery_app beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - capture_network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # ==================== CAPTURE WORKERS ====================
  celery-worker-capture-1:
    build: .
    command: celery -A celery_app worker --loglevel=info --pool=solo --max-tasks-per-child=5 --hostname=capture1@%h --queues=capture
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - CELERYD_PREFETCH_MULTIPLIER=1
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - capture_network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  celery-worker-capture-2:
    build: .
    command: celery -A celery_app worker --loglevel=info --pool=solo --max-tasks-per-child=5 --hostname=capture2@%h --queues=capture
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - CELERYD_PREFETCH_MULTIPLIER=1
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - capture_network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # ==================== DETECTION WORKERS ====================
  celery-worker-detection-1:
    build: .
    command: celery -A celery_app worker --loglevel=info --pool=solo --max-tasks-per-child=5 --hostname=detection1@%h --queues=detection
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - CELERYD_PREFETCH_MULTIPLIER=1
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - capture_network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  celery-worker-detection-2:
    build: .
    command: celery -A celery_app worker --loglevel=info --pool=solo --max-tasks-per-child=5 --hostname=detection2@%h --queues=detection
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - CELERYD_PREFETCH_MULTIPLIER=1
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - capture_network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  flower:
    build: .
    command: celery -A celery_app flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
    env_file:
      - .env
    depends_on:
      - redis
      - celery-worker-capture-1
    restart: unless-stopped
    networks:
      - capture_network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  redis_data:

networks:
  capture_network:
    driver: bridge