server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.31.20.167:3100/loki/api/v1/push

scrape_configs:
  # ==================== Docker Container Logs ====================
  - job_name: docker-containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          server: app-server
          environment: production
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream:
          tag:
      - output:
          source: output

  # ==================== System Logs ====================
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          server: app-server
          __path__: /var/log/*.log

  # ==================== Celery Workers Logs ====================
  - job_name: celery-workers
    static_configs:
      - targets:
          - localhost
        labels:
          job: celery
          server: app-server
          service: celery
          __path__: /var/lib/docker/containers/*celery*.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # ==================== Redis Logs ====================
  - job_name: redis-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: redis
          server: app-server
          service: redis
          __path__: /var/lib/docker/containers/*redis*.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # ==================== Flower Logs ====================
  - job_name: flower-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: flower
          server: app-server
          service: flower
          __path__: /var/lib/docker/containers/*flower*.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # ==================== Telegram Bot Logs ====================
  - job_name: telegram-bot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: telegram-bot
          server: app-server
          service: telegram
          __path__: /var/lib/docker/containers/*telegram-bot*.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output